### ISSUE TITLE
Add a confirmation dialog before removing the version

### ISSUE THREAD

**Issue by douglascrp** [keensoft/alfresco-remove-version#1]
It would be nice to have a dialog asking the user to confirm the version removal.

**Comment by angelborroy-ks** [comment]
Your PRs will be always welcomed!

**Comment by douglascrp** [comment]
@angelborroy-ks Done

**Comment by angelborroy-ks** [comment]
Did you tested it? When using default `run.sh` from SDK project, removing button is not showed...

**Comment by angelborroy-ks** [comment]
Ah, ok, I forgot to include the `GROUP`... Testing again!

**Comment by angelborroy-ks** [comment]
Nice, it works superb! Closing and releasing!
